version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'

  postgres:
    container_name: adminchurch-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres


  pgadmin:
    links:
      - postgres:postgres
    container_name: adminchurch-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rsperlongo@outlook.com
      PGADMIN_DEFAULT_PASSWORD: adminchurch@123
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  mongo-data:

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
